ARG EXIST_VERSION=6.2.0
ARG BUILD=local

FROM ghcr.io/eeditiones/builder:latest AS builder

ARG APP_NAME=tei-publisher-app
ARG APP_REPO=https://github.com/eeditiones/tei-publisher-app.git
ARG APP_TAG_OR_BRANCH=master

WORKDIR /tmp

# jinks-templates is not yet available in the public repo, so we need to clone and build it
RUN  git clone https://github.com/eeditiones/jinks-templates.git \
    && cd jinks-templates \
    && git checkout ${TEMPLATING_VERSION} \
    && ant;

# Build the main app configured in the docker-compose.yml
{% for app in publisher.apps %}
RUN  git clone {{app.repo}} \
    && cd {{app.name}} \
    {% if app.tag_or_branch is defined and app.tag_or_branch %}
    && echo Checking out {{app.tag_or_branch}} \
    && git checkout {{app.tag_or_branch}} \
    {% endif %}
    {% if app.local_webcomponents is defined and app.local_webcomponents %}
    && sed -i 's/$config:webcomponents :=.*;/$config:webcomponents := "local";/' modules/config.xqm \
    {% endif %}
    {% if app.prebuild is defined %}
    && {{ app.prebuild }} \
    {% endif %}
    && ant {% if app.local_webcomponents is defined and app.local_webcomponents %}xar-local{% endif %}
    {% raw %}

    {% endraw %}
{% endfor %}

FROM ghcr.io/jinntec/base:${EXIST_VERSION}

ARG JWT_VERSION=2.0.0
ARG CRYPTO_VERSION=6.0.1

ARG APP_NAME=tei-publisher-app
ARG USR=nonroot:nonroot
USER ${USR}

ADD --chown=${USR} http://exist-db.org/exist/apps/public-repo/public/expath-crypto-module-${CRYPTO_VERSION}.xar /exist/autodeploy
ADD --chown=${USR} http://exist-db.org/exist/apps/public-repo/public/jwt-${JWT_VERSION}.xar /exist/autodeploy

COPY --from=builder --chown=${USR} /tmp/jinks-templates/build/*.xar /exist/autodeploy/_jinks-templates.xar

# replace my-edition with name of your app
{% for app in publisher.apps %}
COPY --from=builder --chown=${USR} /tmp/{{app.name}}/build/*.xar /exist/autodeploy/
{% endfor %}

ARG HTTP_PORT=8080
ARG HTTPS_PORT=8443

ARG NER_ENDPOINT=http://localhost:8001
ARG CONTEXT_PATH=auto
ARG PROXY_CACHING=false

ENV JDK_JAVA_OPTIONS="\
    -Dteipublisher.ner-endpoint=${NER_ENDPOINT} \
    -Dteipublisher.context-path=${CONTEXT_PATH} \
    -Dteipublisher.proxy-caching=${PROXY_CACHING}"

# pre-populate the database by launching it once
RUN [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l" ]

EXPOSE ${HTTP_PORT} ${HTTPS_PORT}